Remove App::before to allow routes be accessible
octobercms/october pull request #4714
Opened 2019-10-23 17:07 UTC by Samuell1

This allows/fixes routes to be visible in route:list and allows to fix route caching for plugins, backend and cms.

Before:
![obrázok](https://user-images.githubusercontent.com/3110002/67416998-271d3280-f5c8-11e9-956f-1105cc83335b.png)

After:
![obrázok](https://user-images.githubusercontent.com/3110002/67416930-081ea080-f5c8-11e9-8aab-a096ec4a7d8d.png)

2019-10-23 18:14 UTC, Samuell1 commented
Before this merge of this PR there needs to be added provider in because i am not sure if somebody forgot to add it when upgrading laravel, but array of providers is missing `Illuminate\Foundation\Support\Providers\RouteServiceProvider`.

2019-10-24 03:29 UTC, LukeTowers commented
@Samuell1 what does that service provider do? It looks like it's just setting up the routes file for a Laravel application, which isn't used by us

2019-10-24 06:41 UTC, Samuell1 commented
@LukeTowers RouteServiceProvider loads and process cached routes when they exists.

2019-10-27 14:18 UTC, bennothommo commented
@Samuell1 Will this have any ramifications with middleware? I assume the `App::before` call that's currently there, albeit being a holdover from Laravel 4, was also set up to run before any middleware?

2019-10-27 16:33 UTC, Samuell1 commented
@bennothommo I dont think so. I tried backedn and it was looking without issues.

2019-10-28 01:05 UTC, bennothommo commented
@Samuell1 I know we've discussed this several times before on Slack, but what were the advantages of caching the routes, especially with regards to October in which everything passes through our main backend Controller class anyway in order to link correctly to installed plugins?

2019-10-28 08:02 UTC, Samuell1 commented
@bennothommo Advantage of this is to allow route:list to work and allow to cache plugin routes.

2019-10-28 08:07 UTC, bennothommo commented
@Samuell1 I mean, performance wise? :stuck_out_tongue:

2019-10-28 08:30 UTC, Samuell1 commented
Yes, it should help with performance if you using multiple routes in plugin (for example like me). @bennothommo

2019-10-28 08:58 UTC, LukeTowers commented
@Samuell1 Does this also support the plugin's routes.php files as well?

2019-10-28 09:23 UTC, Samuell1 commented
@LukeTowers Yes, thats why i was doing this in first place.

For example my plugin routes now are shown in route:list :
![obrázok](https://user-images.githubusercontent.com/3110002/67666892-01e44780-f96d-11e9-9d2c-a78b1ff5aae2.png)

2019-11-07 09:16 UTC, daftspunk commented
This appears ok on the surface but I think it would have to be thoroughly tested because it involves modifying the order of events.

2019-11-08 11:08 UTC, Samuell1 commented
@daftspunk Yep, i think we can add tests for this if there is a way to test somehow routing events and what you think about this https://github.com/octobercms/october/pull/4714#issuecomment-545570609 ? Will be better to make OCMS own RouterProvider or reuse from illuminate?

2019-11-18 11:17 UTC, Samuell1 commented
Looks like Debugbar plugin that extending router trough vendor package has issue when App::before is removed from routes files. I am not sure why this happens but maybe Router is not initialized correctly?

2020-06-26 02:56 UTC, bennothommo commented
@Samuell1 would you be willing to see if this will work with the L6 upgrade, and target your PR for that?

2020-06-26 06:24 UTC, LukeTowers commented
@bennothommo @Samuell1 this is on my todo list to review, if you wait about a month I'll probably get to it then. There's some other changes that have to be made in connection to this.

2020-06-26 06:41 UTC, bennothommo commented
@LukeTowers should we still target it for L6?

2020-06-26 06:50 UTC, Samuell1 commented
@LukeTowers @bennothommo i was talking long time ago with @daftspunk about this, he said he did it different or something now iam not sure if i should close this or?

2020-06-26 08:46 UTC, LukeTowers commented
@Samuell1 leave it for now so we remember to do this. @bennothommo yeah, we'd be targetting L6 at least, if not after the L6 build gets released.

2020-08-30 07:44 UTC, Samuell1 commented
@LukeTowers @bennothommo Looks like Laravel 8 will support closures for caching too maybe it can reimplemented forward in ocms too.

2020-08-30 15:53 UTC, bennothommo commented
@Samuell1 isn't that something that's already supported in L6? https://laravel.com/docs/6.x/cache#retrieving-items-from-the-cache

Or are we talking about something else?

2020-08-30 16:29 UTC, Samuell1 commented
@bennothommo its different Cache just saves value of that closure but for routes you need to have cached the closure to return value.

2020-08-31 01:30 UTC, bennothommo commented
@Samuell1 ah I see. Do you have a link to some docs or an announcement about the feature?

2020-08-31 02:20 UTC, bennothommo commented
@Samuell1 never mind, saw your message on Slack.

For reference: https://www.georgebuckingham.com/laravel-8-new-features/

2020-11-20 21:59 UTC, LukeTowers commented
@Samuell1 is this still something that you want merged?

2020-11-21 02:05 UTC, bennothommo commented
This will need to be adjusted to implement changes done with the L6 upgrade - mainly changing `{slug}` to `{slug?}`.

2020-11-21 02:05 UTC, bennothommo requested changes

2020-11-21 02:05 UTC, bennothommo commented on modules/backend/routes.php
> +        Route::any('{slug}', 'Backend\Classes\BackendController@run')->where('slug', '(.*)?');
```suggestion
        Route::any('{slug?}', 'Backend\Classes\BackendController@run')->where('slug', '(.*)?');
```

2020-11-21 02:05 UTC, bennothommo commented on modules/cms/routes.php
> +Route::any('{slug}', 'Cms\Classes\CmsController@run')->where('slug', '(.*)?')->middleware('web');
```suggestion
Route::any('{slug?}', 'Cms\Classes\CmsController@run')->where('slug', '(.*)?')->middleware('web');
```

2020-11-22 10:45 UTC, Samuell1 commented
@bennothommo yes but @daftspunk had some ideas how to make it work without effecting order of route initialization but iam not sure now if he did something more.

2021-03-04 11:09 UTC, daftspunk commented
Hi @Samuell1. I can confirm it will be fixed in the new version of October CMS coming out soon. It will include route caching. Closing for now

2021-03-04 11:09 UTC, closed without merging