Allow user to set preference if they want tree list to be expanded by default
octobercms/october pull request #5102
Opened 2020-06-01 21:48 UTC by ericp-mrel

This change implements the ability for a user in the back-end to be able to set a preference where they can decide if they want a tree list to be expanded by default or not. This change also makes it much easier to be able to open/close all tree list nodes (assuming they don't have a preference set by opening/closing them manually).

The initial default of the tree list is being expanded or not is inherited from the list config.

![Screenshot_2020-06-01 Category list OctoberCMS(2)](https://user-images.githubusercontent.com/63664924/83458196-abba1400-a427-11ea-9a1d-6a003ac28ab3.png)

Tree nodes are expanded once changing the setting.
![Screenshot_2020-06-01 Category list OctoberCMS(1)](https://user-images.githubusercontent.com/63664924/83458159-92b16300-a427-11ea-914e-fa6915b6fb4d.png)

2020-06-01 22:27 UTC, LukeTowers commented
@ericp-mrel I like the concept, but could we put it in the list header instead as a expand / collapse all button next to the check box?

2020-06-05 22:39 UTC, LukeTowers commented
Just post a screenshot when you're ready.

2020-06-16 14:52 UTC, ericp-mrel commented
Sorry this is taking so long, I've got a lot going on and haven't been able to find time to finish implementing the rest of this.

Once I add the last part of functionality I'll mark this is ready for merging. The last part I need to implement is detecting if all tree nodes have been collapsed and then making sure the toggle all icon switches to expand all nodes so the user doesn't need to click the button twice to collapse all first and then expand all.

2020-07-01 22:56 UTC, ericp-mrel commented
@LukeTowers  I think I've finally got this is a state I am satisfied with.

When default state of `$treeExpanded = false`, clicking the toggle tree button will expand all nodes and set the `$treeExpanded = true` preference.

![image](https://user-images.githubusercontent.com/63664924/86298149-b00e5400-bbc2-11ea-9840-5a56bce3d433.png)

Then, when at least one node is expanded, the toggle tree button will change to collapse all tree nodes.

![image](https://user-images.githubusercontent.com/63664924/86298219-dc29d500-bbc2-11ea-9e8b-d336af2dc3c6.png)

If all nodes are manually collapsed, the `$treeExpanded = false` preference will be set and the toggle tree button will then change to expanding all nodes.

![image](https://user-images.githubusercontent.com/63664924/86298382-3c207b80-bbc3-11ea-9bd5-56f22d9a5008.png)


I decided to make the toggle tree button default to collapsing nodes when possible since that seems to be the most common UX pattern when working with tree lists when I was looking around.

Let me know what you think and if there's anything else you think should be adjusted/changed.

2020-10-20 17:06 UTC, mjauvin requested changes

2020-10-20 17:06 UTC, mjauvin commented on modules/backend/traits/SessionMaker.php
> +    }
```suggestion
    protected function forgetSession($keys)
    {
        $sessionId = $this->makeSessionId();
        $currentStore = $this->getSession();
        Arr::forget($currentStore, $keys);
        Session::put($sessionId, base64_encode(serialize($currentStore)));
    }
```

2020-10-20 17:06 UTC, mjauvin commented on modules/backend/traits/SessionMaker.php
> +     */
```suggestion
     * @return void
     */
```

2020-10-20 17:06 UTC, mjauvin commented on modules/backend/widgets/Lists.php
> +use October\Rain\Support\Str;
```suggestion
use Str;
```

2020-10-20 17:06 UTC, mjauvin commented on modules/backend/widgets/Lists.php
> +
The previous if/elseif code block should be restructured to NOT repeat the code twice.

2020-10-20 17:06 UTC, mjauvin commented on modules/backend/widgets/Lists.php
> +        } elseif (! $expandNode && $this->isAllNodesCollapsed()) {
```suggestion
        } elseif (!$expandNode && $this->isAllNodesCollapsed()) {
```

2020-10-20 17:06 UTC, mjauvin commented on modules/backend/widgets/Lists.php
> +        if (! $this->treeExpanded && $expandNode) {
```suggestion
        if (!$this->treeExpanded && $expandNode) {
```

2020-10-20 17:06 UTC, mjauvin commented on modules/backend/widgets/Lists.php
> +        $this->toggleTreeExpanded = $this->getSession('tree_toggle_expanded', ! $this->treeExpanded);
```suggestion
        $this->toggleTreeExpanded = $this->getSession('tree_toggle_expanded', !$this->treeExpanded);
```

2020-10-20 17:06 UTC, mjauvin commented on modules/backend/widgets/Lists.php
> +        $this->toggleTreeExpanded = ! $this->toggleTreeExpanded;
```suggestion
        $this->toggleTreeExpanded = !$this->toggleTreeExpanded;
```

2020-10-20 17:29 UTC, mjauvin requested changes

2020-10-20 17:29 UTC, mjauvin commented on modules/backend/widgets/Lists.php
> +        if (! $this->showTree) {
```suggestion
        if (!$this->showTree) {
```

2020-10-20 17:38 UTC, mjauvin requested changes

2020-10-20 17:38 UTC, mjauvin commented on modules/backend/widgets/Lists.php
> +        $expandNode = ! post('status');
```suggestion
        $expandNode = !post('status');
```

2020-11-20 08:47 UTC, LukeTowers requested changes

2020-11-20 08:47 UTC, LukeTowers commented on modules/backend/traits/SessionMaker.php
> +use October\Rain\Support\Arr;
```suggestion
use Arr;
```

2020-11-20 08:47 UTC, LukeTowers commented on modules/backend/traits/SessionMaker.php
> +     * @return void
```suggestion
     * Removes one or many items from the widget session data.
     *
     * @param string|array $keys Keys to be removed from the widget session data
     * @return void
```

2020-11-20 08:47 UTC, LukeTowers commented on modules/backend/widgets/Lists.php
> +use Str;
Move this above Html; please

2020-11-20 08:47 UTC, LukeTowers commented on modules/backend/widgets/Lists.php
> +
```suggestion
        $this->showSorting = $this->showPagination = false;
        $this->treeExpanded = $this->getSession('tree_expanded', $this->treeExpanded);
        $this->toggleTreeExpanded = $this->getSession('tree_toggle_expanded', !$this->treeExpanded);
```

2020-12-02 03:14 UTC, ericp-mrel commented on modules/backend/widgets/Lists.php
> +
What do you think about writing like this? I'm not sure this block is common enough to really needing it to be in its own method.

```suggestion
    public function onToggleTreeNode()
    {
        $this->putSession('tree_node_status_' . post('node_id'), post('status') ? 0 : 1);

        $expandNode = !post('status');

        if ((!$this->treeExpanded && $expandNode) || (!$expandNode && $this->isAllNodesCollapsed())) {
            $this->treeExpanded = false;
            $this->putSession('tree_expanded', $this->treeExpanded);
        }

        if (!$this->treeExpanded && $expandNode) {
            /*
             * When the tree is collapsed and the user expands a node,
             * make sure the tree expanded preference is set to false
             * and the toggle button is set to collapse all nodes.
             * The toggle nodes button should always default to collapsing nodes,
             * unless all nodes are already collapsed.
             */

            $this->toggleTreeExpanded = false;
            $this->putSession('tree_toggle_expanded', $this->toggleTreeExpanded);
        } elseif (!$expandNode && $this->isAllNodesCollapsed()) {
            /*
             * If the user is collapsing a node and all nodes are now collapsed,
             * make sure the tree expanded preference is set,
             * and change the toggle button to expand all nodes.
             */

            $this->toggleTreeExpanded = true;
            $this->putSession('tree_toggle_expanded', $this->toggleTreeExpanded);
        }

        return $this->onRefresh();
    }
```

2020-12-02 03:30 UTC, mjauvin commented on modules/backend/widgets/Lists.php
> +
In both versions, the logic seems wrong to me. There has to be a simpler / cleaner / more readable way to write this, no?

2020-12-02 03:31 UTC, mjauvin commented on modules/backend/widgets/Lists.php
> +
But if I have to choose one version, I prefer the former.

2020-12-02 03:37 UTC, mjauvin commented on modules/backend/widgets/Lists.php
> +
Yeah, looking at it again, the previous version is fine, sorry.

2021-02-01 08:49 UTC, LukeTowers commented
@mjauvin what's the current status on this?

2021-02-01 13:15 UTC, mjauvin commented
@LukeTowers I don't know, I am not the author of the PR.

2021-02-01 14:35 UTC, ericp-mrel commented
This PR is done on my end since I've made all of the requested changes.
Unless anyone has any ideas on how to better simplify the logic for this, but this is about as simple as I could make it.

2021-02-01 15:28 UTC, LukeTowers commented
@ericp-mrel can you merge develop back into your branch? I'll review this in some more depth when I have some more time, probably after 1.1.2 is released.

2021-02-06 17:56 UTC, ericp-mrel commented
> @ericp-mrel can you merge develop back into your branch? I'll review this in some more depth when I have some more time, probably after 1.1.2 is released.

I've rebased onto the develop branch, but I had to do a merge before I was able to push to my feature branch. Hopefully I did that correctly.

2021-02-07 07:20 UTC, LukeTowers commented
@ericp-mrel looks like nope, it's screwed up. Please resubmit on a new branch fresh from the current develop branch.

2021-04-28 00:29 UTC, daftspunk commented
This doesn't seem like the right way to approach this. I've made a note to address the ability to expand/collapse all in our internal tracker. Thanks

2021-04-28 00:29 UTC, closed without merging